config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :eateries
  root 'welcome#home'
  get 'about' => "welcome#about"
  get "user" => 'user#index'
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/eatery.rb
class Eatery < ApplicationRecord
	validates :name, :description, :address_state, :phone,
			  presence: { :message => "Cannot be blank"}
	validates :description, length: { maximum: 300 }
	validates :address_state, length: {maximum: 2}
	belongs_to :user
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	validates :party_size, :date, :time,
	presence: { :message => "Cannot be Blank"}

	belongs_to :resturant
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/eateries_controller.rb
class EateriesController < ApplicationController
  before_action :set_eatery, only: [:show, :edit, :update, :destroy]

  # GET /eateries
  # GET /eateries.json
  def index
    @eateries = Eatery.all
  end

  # GET /eateries/1
  # GET /eateries/1.json
  def show
    @reservation = Reservation.new
  end

  # GET /eateries/new
  def new
    @eatery = Eatery.new
  end

  # GET /eateries/1/edit
  def edit
  end

  # POST /eateries
  # POST /eateries.json
  def create
    @eatery = Eatery.new(eatery_params)
    @eatery.user_id = current_user.id
    respond_to do |format|
      if @eatery.save
        format.html { redirect_to @eatery, notice: 'Eatery was successfully created.' }
        format.json { render :show, status: :created, location: @eatery }
      else
        format.html { render :new }
        format.json { render json: @eatery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eateries/1
  # PATCH/PUT /eateries/1.json
  def update
    # one could add some validaiton here to chekc that the
    # current user matches the user associated with the eatery
    respond_to do |format|
      if @eatery.update(eatery_params)
        format.html { redirect_to @eatery, notice: 'Eatery was successfully updated.' }
        format.json { render :show, status: :ok, location: @eatery }
      else
        format.html { render :edit }
        format.json { render json: @eatery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eateries/1
  # DELETE /eateries/1.json
  def destroy
    # one could add some validaiton ehre to chekc that the
    # current user matches the user assocaited with the eatery
    # if current user.id != @eatery.user_id
    #    raise 'Invalid user error'
    # end
    @eatery.destroy
    respond_to do |format|
      format.html { redirect_to eateries_url, notice: 'Eatery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eatery
      @eatery = Eatery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def eatery_params
      params.require(:eatery).permit(:name, :description, :address_city, :address_street, :address_state, :address_zip, :phone)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:email, :date, :time, :name, :party_size, :user_id, :eatery_id, :phone)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :authenticate_user!
  
	def index
  	end
  
  	def delete
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  	if user_signed_in?
  		redirect_to user_path
  	end
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eateries_helper.rb
module EateriesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/resturants_helper.rb
module ResturantsHelper
end

app/helpers/user_helper.rb
module UserHelper
	
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/eateries/_form.html.erb
<%= form_for(@eatery) do |f| %>
  <% if @eatery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(eatery.errors.count, "error") %> prohibited this eatery from being saved:</h2>

      <ul>
      <% eatery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  </div>

  <div class="field">
  <%= f.label :description %><br>
  <%= f.text_field :description %>
  </div>

  <div class="field">
  <%= f.label :phone %><br>
  <%= f.text_field :phone %>
  </div>

  <div class="field">
  <%= f.label :address_street %><br>
  <%= f.text_field :address_street %>
  </div>

  <div class="field">
  <%= f.label :address_zip %><br>
  <%= f.text_field :address_zip %>
  </div>

  <div class="field">
  <%= f.label :address_city %><br>
  <%= f.text_field :address_city %>
  </div>

  <div class="field">
  <%= f.label :address_state %><br>
  <%= f.text_field :address_state %>
  </div>

  <div class="actions">
  <%= f.submit %>
  </div>

<% end %>

app/views/eateries/edit.html.erb
<h1>Editing Eatery</h1>

<%= render 'form', eatery: @eatery %>

<%= link_to 'Show', @eatery %> |
<%= link_to 'Back', eateries_path %>

app/views/eateries/index.html.erb
<p id="notice"><%= notice %></p>

<h1> 
  <span class="glyphicon glyphicon-fire"></span> The Works <span class="glyphicon glyphicon-fire"></span> 
</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eateries.each do |eatery| %>
      <tr>
        <td><%= link_to eatery.name, eatery %></td>
        <td><%= link_to 'Edit', edit_eatery_path(eatery) %></td>
        <td><%= link_to 'Destroy', eatery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Eatery', new_eatery_path %>

app/views/eateries/new.html.erb
<h1>New Eatery</h1>

<%= render 'form', eatery: @eatery %>

<%= link_to 'Back', eateries_path %>

app/views/eateries/show.html.erb
<h1><%= @eatery.name%></h1>
<h3>Phone Number <br> <%= @eatery.phone %></h3>
<p> <%= @eatery.description %></p>

<h3> Address: </h3>
<p><%= @eatery.address_street %></p>
<% if @eatery.address_street2? %>
<p><%= @eatery.address_street2 %></p>
<% end %>
<p><%= @eatery.address_city %></p>
<p><%= @eatery.address_state %></p>

<%= render 'reservations/new' %>

<%= link_to 'Edit', edit_eatery_path(@eatery) %> |
<%= link_to 'Back', eateries_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "DevineEats", root_path, class: "navbar-brand" %>

  </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Account Settings", root_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Log out", destroy_user_session_path, method: :get %></li>
        <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
        <li><%= link_to root_path do %>
          <span class="glyphicon glyphicon-shopping-cart"></span> 
        <% end %>
    </ul>
   </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resturant</title>
     <%= render 'layouts/header' %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <%= csrf_meta_tags %>
  </head>

    <body>
      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_for(reservation) do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/_new.html.erb
<h1> Make a reservation! </h1>
<% if @reservation.errors.any? %>
<ul class="error_list">
  <% @reservation.errors.full.messages.each do |msg| %>
  <li><%= msg %> </li>
  <% end %>
</ul>
  <% end %>

  <%= form_for(@reservation) do |f| %>

	<div class="field">
  	<%= f.label :email %> <br>
  	<%= f.text_field :email %>
  	</div>

  	<div class="field">
  	<%= f.label :party_size %> <br>
  	<%= f.number_field :party_size %>
  	</div>

  	<div class="field">
  	<%= f.label :date %> <br>
  	<%= f.date_select :date %>

  	<div class="field">
  	<%= f.label :time %> <br>
  	<%= f.time_select :time, ampm: true %>
  	</div>

  	<div>
  <%= f.hidden_field :eatery_id, :value => @eatery_id %>
  <br>
  <div class ="actions">
    <%= f.submit %>
  </div>
  <% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/user/index.html.erb
<h1> 
	<span class="glyphicon glyphicon-fire"></span> The Works <span class="glyphicon glyphicon-fire"></span> 
</h1>

	<div class="dropdown">
	  <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
	    Cuisine
	    <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
	    <li><a href="#">American</a></li>
	    <li><a href="#">Mexican</a></li>
	    <li><a href="#">Asian</a></li>
	    <li><a href="#">Italian</a></li>
	    <li role="separator" class="divider"></li>
	    <li><a href="#">Reccommended</a></li>
	  </ul>
	</div>

app/views/welcome/about.html.erb
<h1> About Devine Eats </h1>
	<p> DevineEats is all about delivering quality food to customers looking for the most flavorful, satisfying, and swell eats.
	</p>

	<p>If you are a resturant owner please sign up. We provided an online platform for customers to effortlessly order your great food. Any traffic generated from this site is subject to a fee from Devine Eats.
	</p>

	<%= link_to "New Resturant Sign up", new_eatery_path, class: "btn btn-default btn-lg" %>

	

app/views/welcome/home.html.erb
	<div class= "jumbotron center">
		<h1>Devine Eats</h1>
		 <% if user_signed_in? %>

	     <% else %>

			<p>
			<%= link_to "Sign In", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	       </p>

	     <% end %>
	</div>